name: 🚀 Despliegue de API a VPS (Producción)

on:
  push:
    branches:
      - Mark-ApiProduccion

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VPS_HOST: ${{ secrets.VPN_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

    steps:
      - name: 🧩 Checkout del código
        uses: actions/checkout@v4

      - name: 📤 Desplegar todo el código fuente (para Build en VPS)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.VPN_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USERNAME }}
          # Subimos TODO (código fuente y .env)
          SOURCE: "./src ./.env.production ./package.json ./package-lock.json" 
          TARGET: "/var/www/uncomerciomas-api/"
          ARGS: "-rltgoDzv --delete" # --delete es importante para limpiar

      - name: 🚀 Ejecutar comandos en el VPS (Build, Instalar, Reiniciar)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPN_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/uncomerciomas-api/
            echo "Instalando dependencias de producción en servidor..."
            # 1. USAR 'npm ci' para una instalación limpia y rápida en CI/CD
            npm ci --only=production
            
            echo "Compilando el código fuente..."
            # 2. USAR 'npx nest build' para solucionar el "nest: not found"
            npx nest build
            
            echo "Reiniciando API con PM2..."
            pm2 reload uc+-api || pm2 start dist/main.js --name "uc+-api"
            pm2 save
            echo "✅ Despliegue y Build en Servidor completado con éxito."